version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo "Phase d'installation : aucune commande supplémentaire"
  pre_build:
    commands:
      - echo "Initialisation de l'environnement"
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain gory --domain-owner 842675983046 --query authorizationToken --output text)
      - echo "Token CodeArtifact récupéré : $CODEARTIFACT_AUTH_TOKEN"  # Vérification
  build:
    commands:
      - echo "Build démarré le $(date)"
      - mvn -B -s settings.xml clean package  # Nettoyage et génération du package (WAR)
  post_build:
    commands:
      - echo "Build terminé le $(date)"

artifacts:
  files:
    - "target/Gory-web-projet.war"
  discard-paths: no

