version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "Récupération du token CodeArtifact..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain gory --domain-owner 842675983046 --query authorizationToken --output text)
  build:
    commands:
      - mvn -B -s settings.xml clean package
  post_build:
    commands:
      - echo "Vérification du fichier .war..."
      - ls -l target/  # Débogage: vérifiez la présence du fichier
artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes
