version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo "Récupération du token CodeArtifact..."
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain gory --domain-owner 842675983046 --query authorizationToken --output text)
  build:
    commands:
      - echo "Compilation et packaging en cours..."
      - mvn -B -s settings.xml clean package  # Combine compile + package
artifacts:
  files:
    - "target/Gory-web-projet.war"
  discard-paths: no
